spring:
  datasource:
    url: "jdbc:mariadb://localhost:3307/bookdot?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true"
    username: "eessoxuv"
    password: "s1234"
    driver-class-name: "org.mariadb.jdbc.Driver"

server:
  port: 8085

--- #
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql : true
        format_sql: true


mvc:
  hiddenmethod:
  filter:
  enabled : true
