spring:
  datasource:
    url: "jdbc:mariadb://localhost:3307/bookdot?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true"
    username: "eessoxuv"
    password: "s1234"
    driver-class-name: "org.mariadb.jdbc.Driver"

mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

jpa:
  database-platform: org.hibernate.dialect.MariaDB103Dialect
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      format_sql: true #To beautify or pretty print the SQL
      show_sql: true #show sql
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
